### ISSUE TITLE
Update land use category resolution

### ISSUE THREAD

**Issue by lewisjared** [openmethane/setup-wrf#12]
## The problem
The 10km grid uses `usgs_10m` for its land use categories when 30s fields are available (`usgs_30s`). 10m resolution is ~300km resolution, but 30s is about 1km according to some random website I found.

@prayner Is there any reason not to use the higher resolution product?

**Comment by prayner** [comment]
In fact 10m is 1/6 degree or about 15km but the point still stands. We
should certainly use the high-res when available. I'd need to look
back at earlier versions of the setup scripts but they did use the 30s
data at some stage.

**Comment by lewisjared** [comment]
Opps my googling skills didn't work apparently.

**Comment by prayner** [comment]
correction from last comment, they still *do* use the 30s res but only
for domain 2 & higher. The namelist.wps reflected cases where domain 1
had a much coarser resolution. I'll test changing this and if it works
we then ... what ... open a PR?

**Comment by prayner** [comment]
This tests out fine once I remember to remove the old geo_em file. The
only change is a setting in namelist.wps. Should I open a PR then
close the issue once it's merged?

**Comment by prayner** [comment]
change is already implemented in namelist.wps so will close
