### ISSUE TITLE
Update the configuration for CMAQ and WRF

### ISSUE THREAD

**Issue by crdanielbusch** [openmethane/setup-wrf#20]
## The motivation

It will be easier for future users to create a correct configuration file if we define the requirements for the individual entries and types in detail and include them in the documentation. 

## The proposed solution

- [x] Store the requirements for the configuration in the docstring of the `CMAQConfig` and `WRFConfig` Class
- [ ] Update the docstring in the class definition according to the latest requirements
- [ ] Test what is the appropriate type for each variable

**Comment by lewisjared** [comment]
Also the NCI configuration for the CMAQ setup should be extracted to JSON file as a starting point for NCI users
